Termproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    #url(r'^', include("home.urls", namespace = "home")),
    url(r'^admin/', admin.site.urls),
    #url(r'^user/', include("user.urls", namespace = "user")),
    url(r'^', TemplateView.as_view(template_name="index.html")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import include,url
from .import views

app_name = "home"

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^tutorial$', views.tutorial, name = "tutorial"),
    url(r'^about$', views.about, name="about"),
]

user/urls.py
from django.conf.urls import url
from .import views

app_name = "user"

urlpatterns = [
    url(r'^register/$', views.register, name = "register"),
    url(r'^login/$', views.login_user, name="login"),
    url(r'^profile/$', views.display_profile, name="profile"),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^profile/create/$', views.create_profile, name="create_profile"),
    url(r'^profile/events/$', views.all_events, name= "all_events"),
    url(r'^profile/events/create/$', views.create_event, name="create_event"),
    url(r'^$', views.logout_user, name="logout"),
    url(r'^profile/events/detail/(?P<event_id>[0-9]+)/$', views.event_detail, 
        name="event_detail"),
    url(r'^profile/events/delete/(?P<event_id>[0-9]+)/$', views.delete_event, 
        name='delete_event'),
    url(r'^profile/events/edit/(?P<event_id>[0-9]+)/$', views.edit_event,
     name='edit_event'),  
    url(r'^profile/my_events/current/$', views.myevents_current, 
        name="myevents_current"),
    url(r'^profile/my_events/past/$', views.myevents_past,name="myevents_past"),
    url(r'^profile/my_events/future/$', views.myevents_future,
        name="myevents_future"),
    url(r'^profile/disease_control/$', views.aggregateUserData, 
        name="disease_control"),
    url(r'^all_events/current/$', views.allevents_current, 
        name="allevents_current"),
    url(r'^all_events/past/$', views.allevents_past, name="allevents_past"),
    url(r'^all_events/future/$', views.allevents_future, 
        name="allevents_future"),
    url(r'^all_events/detail/(?P<event_id>[0-9]+)/$', views.otherevent_detail, 
        name="otherevent_detail"),
    url(r'^friends/$', views.display_friends, name="display_friends"),
    url(r'^user/detail/(?P<user_id>[0-9]+)/$', views.user_detail, 
        name='user_detail'),
    url(r'^friends/search/$', views.friends_search, name="friends_search"),
    url(r'^friends/search/send_request/(?P<user_id>[0-9]+)/$', 
        views.send_request, name = 'send_request'),
    url(r'^friends/request/$', views.display_request, name='display_request'),
    url(r'^friends/request/detail/(?P<message_id>[0-9]+)/$', 
        views.request_detail, name='request_detail'),
    url(r'^friends/request/detail/sent/(?P<message_id>[0-9]+)/$', 
        views.request_detail_sent, name='request_detail_sent'),
    url(r'^friends/request/detail/accept/(?P<message_id>[0-9]+)/$', 
        views.accept_friendship, name='accept_friendship'),
    url(r'^friends/request/detail/reject/(?P<message_id>[0-9]+)/$', 
        views.reject_friendship, name='reject_friendship'),
    url(r'^friends/detail/delete/friend/(?P<user_id>[0-9]+)/$', 
        views.delete_friend, name='delete_friend'),
    url(r'^friends/events/$', views.friends_events, name="friends_events"),
    url(r'^friends/events/past/$', views.friends_events_past, 
        name="friends_events_past"),
    url(r'^friends/events/current/$', views.friends_events_current, 
        name="friends_events_current"),
    url(r'^friends/events/future/$', views.friends_events_future, 
        name="friends_events_future"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    context = {} #information that I am going to pass in
    return render(request, "home/homepage.html", context)

def tutorial(request):
    context = {}
    return render(request, 'home/tutorial.html', context)

def about(request):
    context = {}
    return render(request, 'home/about.html', context)

home/templates/home/about.html
{% extends 'home/homebase.html' %}
{% block title %}SmileyPage About{% endblock %}
{% block body %}

<div class="container">


        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Brief Introduction</strong>
                    </h2>
                    <hr>
                    <p>Hi, this is Yue Xu, from Carnegie Mellon University. This is my term project for course 15-112. I hope people could find this website convenient for them to find friends and share great things.</p>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About:
                        <strong>Find Your Study Buddy and Lunch Buddy</strong>
                    </h2>
                    <hr>
                        <p>Leaving high school and entering college, students are no longer able to eat lunch and study together with friends all the time. Most college students say that “people should get used to do things alone because loneliness is such a common thing in college”. In Carnegie Mellon University, everyone has a different schedule and is busy meeting different deadlines. Time becomes so valuable yet scarce. It is uneasy to find someone to eat lunch with or study together just at the “right time”. </p>
                </div>
            </div>
        </div>

    </div>














{% endblock %}

home/templates/home/homebase.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}SmileyPage Homepage{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"/>

    <!-- Custom CSS -->
    <link href="/static/css/smileypage.css"  rel="stylesheet"/>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"  rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic"  rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Lobster"/>
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Dancing Script"/>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body background={%block background%} "/static/images/bg-01.jpg"{% endblock %}>

    <div class="brand">Diagnosis</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'home:index' %}">Diagnosis</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'home:index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'user:login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'user:register' %}">Signup</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- /.container -->
    {% block body %}
    {% endblock %}
    <!-- jQuery -->
    <script src="/static/js/jquery.js" ></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

home/templates/home/homepage.html
<!DOCTYPE html>
{% extends 'home/homebase.html' %}
{% block title %}SmileyPage Home Page{% endblock %}
{% block body %}
{% load staticfiles %}
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="/static/img/Malaria-vaccine.jpg"  alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="/static/img/typhoid.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="/static/img/who.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Diagnosis</h1>
                    <hr class="tagline-divider">
                    <h2>
<!--                         <small>
                            <strong></strong>
                        </small> -->
                    </h2>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/home/tutorial.html
{% extends 'home/homebase.html' %}
{% block title %}SmileyPage Tutorial{% endblock %}
{% block body %}
<div class="container" align="center">
        <div class="row" align="center">
            <div class="box" align="center">
                <div class="col-lg-12" align="center">
<iframe width="1000" height="600" autohide="2"
src="http://www.youtube.com/embed/5rg5HxEkxLE?autoplay=0">
</iframe>
</div>
</div>
</div>
</div>

{% endblock %}