Termproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    #url(r'^', include("home.urls", namespace = "home")),
    url(r'^admin/', admin.site.urls),
    #url(r'^user/', include("user.urls", namespace = "user")),
    url(r'^', TemplateView.as_view(template_name="index.html")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import include,url
from .import views

app_name = "home"

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^tutorial$', views.tutorial, name = "tutorial"),
    url(r'^about$', views.about, name="about"),
]

user/urls.py
from django.conf.urls import url
from .import views

app_name = "user"

urlpatterns = [
    url(r'^register/$', views.register, name = "register"),
    url(r'^login/$', views.login_user, name="login"),
    url(r'^profile/$', views.display_profile, name="profile"),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^profile/create/$', views.create_profile, name="create_profile"),
    url(r'^profile/events/$', views.all_events, name= "all_events"),
    url(r'^profile/events/create/$', views.create_event, name="create_event"),
    url(r'^$', views.logout_user, name="logout"),
    url(r'^profile/events/detail/(?P<event_id>[0-9]+)/$', views.event_detail, 
        name="event_detail"),
    url(r'^profile/events/delete/(?P<event_id>[0-9]+)/$', views.delete_event, 
        name='delete_event'),
    url(r'^profile/events/edit/(?P<event_id>[0-9]+)/$', views.edit_event,
     name='edit_event'),  
    url(r'^profile/my_events/current/$', views.myevents_current, 
        name="myevents_current"),
    url(r'^profile/my_events/past/$', views.myevents_past,name="myevents_past"),
    url(r'^profile/my_events/future/$', views.myevents_future,
        name="myevents_future"),
    url(r'^profile/disease_control/$', views.aggregateUserData, 
        name="disease_control"),
    url(r'^all_events/current/$', views.allevents_current, 
        name="allevents_current"),
    url(r'^all_events/past/$', views.allevents_past, name="allevents_past"),
    url(r'^all_events/future/$', views.allevents_future, 
        name="allevents_future"),
    url(r'^all_events/detail/(?P<event_id>[0-9]+)/$', views.otherevent_detail, 
        name="otherevent_detail"),
    url(r'^friends/$', views.display_friends, name="display_friends"),
    url(r'^user/detail/(?P<user_id>[0-9]+)/$', views.user_detail, 
        name='user_detail'),
    url(r'^friends/search/$', views.friends_search, name="friends_search"),
    url(r'^friends/search/send_request/(?P<user_id>[0-9]+)/$', 
        views.send_request, name = 'send_request'),
    url(r'^friends/request/$', views.display_request, name='display_request'),
    url(r'^friends/request/detail/(?P<message_id>[0-9]+)/$', 
        views.request_detail, name='request_detail'),
    url(r'^friends/request/detail/sent/(?P<message_id>[0-9]+)/$', 
        views.request_detail_sent, name='request_detail_sent'),
    url(r'^friends/request/detail/accept/(?P<message_id>[0-9]+)/$', 
        views.accept_friendship, name='accept_friendship'),
    url(r'^friends/request/detail/reject/(?P<message_id>[0-9]+)/$', 
        views.reject_friendship, name='reject_friendship'),
    url(r'^friends/detail/delete/friend/(?P<user_id>[0-9]+)/$', 
        views.delete_friend, name='delete_friend'),
    url(r'^friends/events/$', views.friends_events, name="friends_events"),
    url(r'^friends/events/past/$', views.friends_events_past, 
        name="friends_events_past"),
    url(r'^friends/events/current/$', views.friends_events_current, 
        name="friends_events_current"),
    url(r'^friends/events/future/$', views.friends_events_future, 
        name="friends_events_future"),
]

user/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Event, HelpRequest
from django.utils.translation import ugettext_lazy as _
from django.forms.extras.widgets import SelectDateWidget
import datetime
from django.forms import DateTimeInput, Textarea, TimeInput
from django.utils.translation import ugettext_lazy as _


class UserForm (forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta: #information about Users
        model = User
        fields = ['username', 'email', 'password']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields =['radius', 'profile_photo', 'location',
        'status']
        labels = {
            'radius':_('Radius of Interest'),
            'profile_photo':_('Profile Photo'),
            'status':_('Your Status'),
            'location':_('Your Location'),
            # 'facebook_page':_('Your Facebook Profile Page URL (optional)'),
        }

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['symptoms', 'date', 'location', 'photo']
        widgets = {
            'date': SelectDateWidget(),
            # 'end_time': forms.TimeInput(format='%H:%M'),
            # 'start_time': forms.TimeInput(format='%H:%M'),
        }
        labels = {
            'symptoms':_('Description'),
            'date':_("Date"),
            'photo':_('Phote of symptoms'),
            'location':_('Location'),
            }


class HelpRequestForm(forms.ModelForm):

    class Meta:
        model = HelpRequest
        fields = ['message']

user/views.py
from .predict import *
from .imageClassify import *

from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, logout, login
from django.views.generic import View
from .forms import UserForm, ProfileForm, EventForm, HelpRequestForm
from django.template import loader
from .models import Event, Profile, User, Connection, HelpRequest
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime
from django.db.models import Q


# aggregate data based on location & range
# select at most 5 keywords of the highest frequencies
from urllib.request import urlopen
import json, string



def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        # email = form.cleaned_data['email']
        user.set_password(password)
        user.save()
        user = authenticate(username = username, password = password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('user:login'))
    context = {'form':form,}
    return render(request, 'user/registration_form.html', context)


def login_user(request):
    login_initial = True
    if request.method=="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        login_initial = False
        if user is not None:
            if user.is_active:
                login(request, user)
                profiles = Profile.objects.filter(user=request.user)
                context = {'user':user, 'profiles':profiles}
                if not profiles:
                    return HttpResponseRedirect(reverse('user:create_profile'))
                else:
                    return HttpResponseRedirect(reverse('user:profile'))
            else:
                return render(request, 'user/login_med.html', {'error_message': 
                           "The user account is not active"})
    if login_initial == False:
        return render(request, 'user/login_med.html', {'error_message': 
        "Either the username or the password is incorrect. Please try again."})
    return render(request, 'user/login_med.html')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def display_profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))

    else:
        user = request.user
        profiles = Profile.objects.filter(user=request.user)
        events = Event.objects.filter(user=request.user).order_by('-date')
        query = request.GET.get("q")
        if query:
            events = events.filter(Q(symptoms__icontains=query) |
                                   Q(date__icontains=query)  | 
                                   Q(prediction__icontains=query)|
                                   Q(location__icontains=query)).distinct()
        return render(request, 'user/profile.html', {'profiles':profiles, 
            'user':user, 'events':events})


def create_profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.user = request.user
            profile.save()
            profiles = Profile.objects.filter(user=request.user)
            return HttpResponseRedirect(reverse('user:profile'))
        context = {'form': form}
    return  render(request, 'user/create_profile.html', context)


def all_events(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        events = Event.objects.all().order_by('-date')
        query = request.GET.get("q")
        if query:
            events = events.filter(Q(symptoms__icontains=query) |
                                   Q(date__icontains=query)  | 
                                   Q(prediction__icontains=query)|
                                   Q(location__icontains=query)|
                            Q(user__username__icontains=query)).distinct()
            events=events.order_by('-date')
        query2 = request.GET.get("l")
        if query2:
            render(request, '')
        context = {"events":events, 'user':user}
    return render(request, 'user/all_events.html', context)



def create_event(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        form = EventForm(request.POST or None)
        if form.is_valid():
            event = form.save(commit = False)
            event.user = request.user
            symptoms_photo = event.photo
            prediction = predict(event.symptoms)
            result = ""
            # create a table later on
            disease, p = prediction[0]
            prob = (math.e**p) *  100
            result = "Disease is " + disease + "with %.2f percent probability\n"%(abs(p))
            # if symptoms_photo != '/static/images/bg-01.jpg':
            #     test = analyze_image(symptoms_photo)
            #     if test:
            #         result = result + "Your skin-disease test is Positive."
            #     else:
            #         result = result + "Your skin-disease test is Negative."
            # else:
            #     result = "aha"
            event.prediction = result
            event.save()
            events = Event.objects.filter(user=request.user)
            return HttpResponseRedirect(reverse('user:profile'))
        context = {'form': form}
    return render(request, 'user/create_event.html', context)


def delete_event(request, event_id):
    event = Event.objects.get(pk = event_id)
    event.delete()
    return HttpResponseRedirect(reverse('user:profile'))


def edit_profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        profile = get_object_or_404(Profile, user=user)
        form=ProfileForm(request.POST or None, instance =profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
        context = {'form':form, 'user':user}
        return render(request, 'user/edit_profile.html', context)

def edit_event(request, event_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        event = get_object_or_404(Event, id=event_id)
        form=EventForm(request.POST or None, instance =event)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:event_detail', 
                args = (event.id,)))
        context = {'form':form, 'user':user}
        return render(request, 'user/create_event.html', context)



def event_detail(request, event_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        event = get_object_or_404(Event, pk = event_id)
        context = {'event':event, 'user':user}
        return render(request, 'user/event_detail.html', context)

def myevents_current(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        profiles = Profile.objects.filter(user=user)
        query = request.GET.get("q")
        events_mine = Event.objects.filter(user=user).order_by('-date')
        events=events_mine.filter(date=datetime.date.today()).order_by('-date')
        if query:
            events =events_mine.filter(Q(symptoms__icontains=query) |
                                   Q(date__icontains=query)  | 
                                   Q(prediction__icontains=query)|
                                   Q(location__icontains=query)|
                            Q(user__username__icontains=query)).distinct()
            events=events.order_by('-date')
        context = {'events':events, 'user':user, 'profiles':profiles}
        return render(request, 'user/profile.html', context)

def myevents_past(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        profiles = Profile.objects.filter(user=user)
        query = request.GET.get("q")
        events_mine = Event.objects.filter(user=user).order_by('-date')
        events=events_mine.filter(date__lt=datetime.date.today()
            ).order_by('-date')
        if query:
            events =events_mine.filter(Q(symptoms__icontains=query) |
                                   Q(date__icontains=query)  | 
                                   Q(prediction__icontains=query)|
                                   Q(location__icontains=query)|
                            Q(user__username__icontains=query)).distinct()
            events=events.order_by('-date')
        context = {'events':events, 'user':user, 'profiles':profiles}
        return render(request, 'user/profile.html', context)

def myevents_future(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:login'))
    else:
        user=request.user
        profiles = Profile.objects.filter(user=user)
        query = request.GET.get("q")
        events_mine = Event.objects.filter(user=user).order_by('-date')
        events=events_mine.filter(date__gt=datetime.date.today()
            ).order_by('-date')
        if query:

user/templates/user/create_event.html
{% extends 'user/base.html' %}
{% block title %}Diagnosis Report Add or Change{% endblock %}

{% block username %}Add or Edit Report{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a Report Here</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'user/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/display_request.html
{% extends 'user/base.html' %}
{% block title %}SmileyPage Friends Request{% endblock %}

{% block username %}{{user.username}}'s SmileyPage -- Friends Request{% endblock %}

{% block body %}
<div class="row">
    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>
                <a href = "{% url 'user:display_friends' %}">Connections List</a>
            </li>
            <li>
                <a href = "{% url 'user:display_request' %}">Connections Request</a>
            </li>
<!--             <li>
                <a href = "{% url 'user:friends_events' %}">Connections' Events</a>
            </li> -->
            <li>
                <a href = "{% url 'user:friends_search' %}">Find New Connections</a>
            </li>
        </ul>
    </nav>
    <div class='col-sm-6'>
        <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>Received Message</li>
        </ul>
        </nav>
    {% if received %}
    {% for message in received %}
    <div class="col-sm-8 col-lg-4">
                <div class="thumbnail"  id="transparent">
                    <div class="caption">
                        <h3>From: {{ message.from_user.username }}</h3>
                        <h4>Sent Time: {{ message.created}}</h4>
                        {% if message.viewed %}
                            <h4>Viewed</h4>
                        {% endif %}
                        {% if message.accepted %}
                            <h4 style="display: inline;">Accepted</h4>
                        {% elif message.rejected %}
                            <h4 style="display: inline;">Rejected</h4>
                        {% endif %}
                        <!-- View Details -->
                        <a href="{% url 'user:request_detail' message.id %}"
                         class="btn btn-primary btn-sm" 
                         role="button">View Details</a>
                    </div>
                </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col-sm-8 col-lg-4">
        <div class="thumbnail"  id="transparent">
            <div class="caption">
                <h2 id='normalLetter'>No Received Connection Request</h2>
            </div>
        </div>
    </div>
    {% endif %}
    </div>

    <div class='col-sm-6'>
        <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>Sent Message</li>
        </ul>
        </nav>
    {% if sent %}
    {% for message in sent %}
    <div class="col-sm-8 col-lg-4">
                    <div class="thumbnail"  id="transparent">
                        <div class="caption">
                            <h3>Send to : {{ message.to_user.username }}</h3>
                            <h4>Sent Time: {{ message.created}}</h4>
                            {% if message.accepted %}
                                <h4 style="display: inline;">Accepted</h4>
                            {% elif message.rejected %}
                                <h4 style="display: inline;">Rejected</h4>
                            {% endif %}
                            <!-- View Details -->
                            <a href="{% url 'user:request_detail_sent' message.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>
                    </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col-sm-8 col-lg-4">
        <div class="thumbnail"  id="transparent">
            <div class="caption">
                <h2 id='normalLetter'>No Sent Connection Request</h2>
            </div>
        </div>
    </div>
    {% endif %}
    </div>
 
</div>

{% endblock %}

user/templates/user/friends.html
{% extends 'user/base.html' %}
{% block title %}Connections{% endblock %}

{% block username %}{{user.username}}'s Homepage -- Connections{% endblock %}

{% block body %}

<div class="row">

    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>
                <a href = "{% url 'user:display_friends' %}">Connections List</a>
            </li>
            <li>
                <a href = "{% url 'user:display_request' %}">Connections Request</a>
            </li>
<!--             <li>
                <a href = "{% url 'user:friends_events' %}">Friends' Events</a>
            </li> -->
            <li>
                <a href = "{% url 'user:friends_search' %}">All Users</a>
            </li>
            <li vertical-align="center">
                <form method = 'GET' action='' style="padding-top:32px;padding-left: 30px">
                <input type='text' name = 'q' placeholder = 'Search Friends' value = '{{request.GET.q }}'/>
                <input type = 'submit' value='Search'/>
                </form>
            </li>
        </ul>
    </nav>

    {% if connections %}
    {% for connection in connections %}
    <div class="col-sm-8 col-lg-3">
                    <div class="thumbnail"  id="transparent">
                        <div class="caption">
                            <h3>{{ connection.username }}</h3><!-- 
                            <h4>{{ connection.status_in_cmu }}</h4> -->
                            <a href="{% url 'user:user_detail' connection.id %}" class="btn btn-primary btn-sm" role="button">View Profile</a>
                            <form action="{% url 'user:delete_connection' connection.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="event_id" value="{{ event.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
    </div>

    {% endfor %}
    {% else %}
    <div class="col-sm-8 col-lg-5">
                    <div class="thumbnail"  id="transparent">
                        <div class="caption">
                        <h2 id="normalLetter">No connections Available~</h2>
                        </div>
                    </div>
    </div>
    {% endif %}

</div>


{% endblock %}

user/templates/user/friends_events.html
{% extends 'user/base.html' %}
{% block title %}Report of Connections{% endblock %}

{% block username %}{{user.username}}'s Homepage -- Connections' Events{% endblock %}

{% block body %}
<div class="row">
    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>
                <a href = "{% url 'user:display_friends' %}">Connections List</a>
            </li>
            <li>
                <a href = "{% url 'user:display_request' %}">Connections Request</a>
            </li>
<!--             <li>
                <a href = "{% url 'user:friends_events' %}">Friends' Events</a>
            </li> -->
            <li>
                <a href = "{% url 'user:friends_search' %}">All Users</a>
            </li>
        </ul>
    </nav>
    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
<!--             <li>
                <a href = "{% url 'user:friends_events_past' %}">Past Events</a>
            </li>
            <li>
                <a href = "{% url 'user:friends_events_current' %}">Current Events</a>
            </li>
            <li>
                <a href = "{% url 'user:friends_events_future' %}">Future Events</a>
            </li> -->
            <li vertical-align="center">
                <form method = 'GET' action='' style="padding-top:32px;padding-left: 30px">
                <input type='text' name = 'q' placeholder = 'Search Friends Events' value = '{{request.GET.q }}'/>
                <input type = 'submit' value='Search'/>
                </form>
            </li>
        </ul>
    </nav>



    {% if events %}
    {% for event in events %}
    <div class="col-sm-8 col-lg-3">
                    <div class="thumbnail"  id="transparent">
                        <a href="{% url 'user:otherevent_detail' event.id %}">
<!--                             {% if event.kind == 'Food' %}
                                <img src="/static/img/train.jpg" style = "width:400px; height:300px;" class="img-responsive">
                            {% elif event.kind == 'Study' %}
                                <img src="/static/img/travel.jpg" style = "width:400px; height:300px;" class="img-responsive"> 
                            {% else %}
                                <img src="/static/img/eiffel.jpg"style = "width:400px; height:300px;"  class="img-responsive">   
                            {% endif %}  -->                           
                        </a>
                        <div class="caption">
                            <h3>{{ event.symptoms }}</h3>
                            <h4>{{ event.prediction }}</h4>
                            <h4>{{ event.date }}</h4>
<!--                             <h4>Start Time: {{ event.start_time }}</h4>
                            <h4>End Time: {{ event.end_time }}</h4> -->
                            <h4>Location: {{event.location}}</h4>
                            <!-- View Details -->
                            <a href="{% url 'user:otherevent_detail' event.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        </div>
                    </div>

    </div>

    {% endfor %}
    {% else %}
    <div class="col-sm-8 col-lg-5">
                    <div class="thumbnail"  id="transparent">
                        <div class="caption">
                        <h2 id="normalLetter">No Records Available~</h2>
                        </div>
                    </div>
    </div>
    {% endif %}

</div>

{% endblock %}

user/templates/user/friends_search.html
{% extends 'user/base.html' %}
{% block title %}Connection Search{% endblock %}

{% block username %}{{user.username}}'s Homepage -- Connection{% endblock %}

{% block body %}
<div class="row">
    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>
                <a href = "{% url 'user:display_friends' %}">Connections List</a>
            </li>
            <li>
                <a href = "{% url 'user:display_request' %}">Connections Request</a>
            </li>
<!--             <li>
                <a href = "{% url 'user:friends_events' %}">Friends' Events</a>
            </li> -->
            <li>
                <a href = "{% url 'user:friends_search' %}">All Users</a>
            </li>
            <li vertical-align="center">
                <form method = 'GET' action='' style="padding-top:32px;padding-left: 50px">
                <input type='text' name = 'q' placeholder = 'Search Users' value = '{{request.GET.q }}'/>
                <input type = 'submit' value='Search'/>
                </form>
            </li>
        </ul>
    </nav>

    {% if profiles %}
    {% for profile in profiles %}
    <div class="col-sm-8 col-lg-3">
        <div class="thumbnail"  id="transparent">
            <a href="{% url 'user:user_detail' profile.user.id %}">
                <img src={{ profile.profile_photo.url }} style = "width:400px; height:300px;" class="img-responsive">
            </a>
            <div class="caption">
                <h3 id='normalLetter'>{{ profile.user.username }}</h3>
                <h4 id='normalLetter'>{{ profile.status }}</h4>
                <a href="{% url 'user:user_detail' profile.user.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
            </div>
        </div>
    </div>

    {% endfor %}
    {% else %}
    <div class="col-sm-8 col-lg-5">
                    <div class="thumbnail"  id="transparent">
                        <div class="caption">
                        <h2 id="normalLetter">No Available User~</h2>
                        </div>
                    </div>
    </div>
    {% endif %}

</div>

{% endblock %}

user/templates/user/login_redirect.html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1;url='{% url "user:profile" %}'">
        <script type="text/javascript">
            window.location.href = '{% url "user:profile" %}'
        </script>
        <title>Page Redirection</title>
    </head>
    <body>
        <!-- Note: don't tell people to `click` the link, just tell them that it is a link. -->
        If you are not redirected automatically, follow the <a href='{% url "user:profile" %}'>link</a>
    </body>
</html>

user/templates/user/request_detail_sent.html
{% extends 'user/base.html' %}
{% block title %}Messages{% endblock %}

{% block username %}{{user.username}}'s Homepage -- Connections{% endblock %}

{% block body %}
<div class="row">
    <nav class="navbar navbar-default" role = "navigation">
        <ul class="nav navbar-nav">
            <li>
                <a href = "{% url 'user:display_friends' %}">Connections List</a>
            </li>
            <li>
                <a href = "{% url 'user:display_request' %}">Connections Request</a>
            </li>
<!--             <li>
                <a href = "{% url 'user:friends_events' %}">Friends' Events</a>
            </li> -->
            <li>
                <a href = "{% url 'user:friends_search' %}">All Users</a>
            </li>
        </ul>
    </nav>

    <div class="box col-lg-6" >
        <div class="col-lg-12" >  
            <hr>
            <h2 class="intro-text text-center">
                <strong>Connections Request</strong>
            </h2>
            <hr>
            <hr class="visible-xs">
            <h3 id='normalLetter'><strong>From:</strong> {{message.from_user.username}}</h3>
            <h3 id='normalLetter'><strong>To:</strong> {{message.to_user.username}}</h3>
            {% if message.message %}
                <h3><strong>Message:</strong></h3>
                <h4 id='normalLetter' style="display: inline;">{{message.message}}</h4>
            {% else %}
                <h3><strong>Message:</strong></h3>
                <h4 id='normalLetter' style="display: inline;">no specific message</h4>
            {% endif %}

            {% if message.accepted %}
                <h4>Accepted</h4>
            {% elif message.rejected %}
                <h4>Rejected</h4>
            {% else %}
                <h4>No Response Yet</h4>
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}